[package]
name = "tracer"
version = "0.2.0"
authors = [
    # author of the original riscv-rust codebase
    "Takahiro <hogehoge@gachapin.jp>",
    # authors of the mofications for Jolt
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>"
]
description = "RISC-V emulator for Jolt"
license = "MIT"
homepage = "https://github.com/a16z/lasso/README.md"
repository = "https://github.com/a16z/lasso"

[dependencies]
fnv = "1.0.7"
