[package]
name = "common"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
strum_macros = "0.25.3"
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
ark-std = "0.4.0"
ark-ec = "0.4.2"
ark-serialize = "0.4.2"
rayon = { version = "^1.8.0" }
