# cargo-features = ["per-package-target"]

[package]
name = "sha3-guest"
version = "0.1.0"
edition = "2021"

# forced-target = "riscv32i-unknown-none-elf"

[features]
guest = []

[lib]
path = "src/main.rs"

[dependencies]
sha3 = { version = "0.10.8", default-features = false }
jolt-sdk = { path = "../../../jolt-sdk" }
